name: 'Archive Build'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

permissions: write-all

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Download package
        run: |
          wget -k https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_${{ github.event.inputs.version }}_amd64.deb
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            microsoft-edge-stable_${{ github.event.inputs.version }}_amd64.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false